# Generated by Django 6.0.5 on 2026-06-06 14:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='message_text',
            field=models.TextField(validators=[django.core.validators.MinLengthValidator(1, 'Message cannot be empty')]),
        ),
    ]
