# Generated by Django 6.0.5 on 2026-06-03 05:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostels', '0001_initial'),
        ('users', '0002_user_college_name_user_phone_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostel',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='hostels/'),
        ),
        migrations.AlterField(
            model_name='hostel',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='hostel',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hostels', to='users.user'),
        ),
        migrations.AlterField(
            model_name='hostel',
            name='rent_amount',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
        migrations.AlterField(
            model_name='hostel',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
