# Generated by Django 6.0.5 on 2026-06-06 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostels', '0003_hostelimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostel',
            name='average_rating',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=3),
        ),
    ]
