# Generated by Django 6.0.5 on 2026-06-08 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostels', '0004_hostel_average_rating'),
        ('users', '0003_user_is_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostelimage',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddIndex(
            model_name='hostel',
            index=models.Index(fields=['rent_amount'], name='idx_hostel_rent'),
        ),
        migrations.AddIndex(
            model_name='hostel',
            index=models.Index(fields=['owner'], name='idx_hostel_owner'),
        ),
        migrations.AddIndex(
            model_name='hostel',
            index=models.Index(fields=['latitude'], name='idx_hostel_lat'),
        ),
        migrations.AddIndex(
            model_name='hostel',
            index=models.Index(fields=['longitude'], name='idx_hostel_lng'),
        ),
        migrations.AddIndex(
            model_name='hostel',
            index=models.Index(fields=['rent_amount', 'owner'], name='idx_hostel_rent_owner'),
        ),
        migrations.AlterModelTable(
            name='hostel',
            table='hostels_hostel',
        ),
    ]
