# Generated by Django 6.0.5 on 2026-06-06 11:36

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hostels', '0003_hostelimage'),
        ('users', '0002_user_college_name_user_phone_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(validators=[django.core.validators.MinValueValidator(1, 'Rating cannot be less than 1'), django.core.validators.MaxValueValidator(5, 'Rating cannot be more than 5')])),
                ('comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('hostel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='hostels.hostel')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='users.user')),
            ],
            options={
                'db_table': 'reviews',
                'constraints': [models.UniqueConstraint(fields=('student', 'hostel'), name='unique_student_hostel_review')],
            },
        ),
    ]
