# Generated by Django 6.0.5 on 2026-06-08 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='owner_reply',
            field=models.TextField(blank=True, null=True),
        ),
    ]
